### ISSUE TITLE
Use new federationlist version

### ISSUE THREAD

**Issue by nikzen** [famedly/synapse-invite-checker#23]
### Description
We need to make sure to use the latest version of the list: https://github.com/gematik/api-vzd/blob/main/src/openapi/I_VZD_TIM_Provider_Services.yaml

### What has changed?
We need to update from version 1.3.1 to 1.3.7. The most important change is, that the domain scheme has changed. We need this new schema to make the /v1/server/findByIk endpoint work.

**Comment by nico-famedly** [comment]
I think we already support that, but we will verify that and possibly add a test.

**Comment by jason-famedly** [comment]
This appears to be already supported as of 1d66a86, so approximately a year. I think the only real difference is that `timAnbieter` is a required field and could be registered as `None`.

I can write tests checking for these fields.

**Comment by nico-famedly** [comment]
The `Domain` schema is not for the federation list, it is for the return values of the `/federation` endpoint and similar.

**Comment by jason-famedly** [comment]
I suppose I was over thinking it. Good, ignore all that then

The last significant change to the schema was in
* [`added timProvider`](https://github.com/gematik/api-vzd/commit/5565c189409fb1b4ecd74ab5a4fcd7ee33bdeaf2)

with an addition of changing `timProvider` to `timAnbieter` here
* [`timProvider -> timAnbieter`](https://github.com/gematik/api-vzd/commit/35f40091051c3e1a229523ad04baf5902f893df0)

Both of which were over a year ago and are already handled
